site_name: Tech-Docs
copyright: Copyright &copy; 2024 Tech Docs
# repo_name: GitHubMotiar/My-Project_II
# repo_url: https://github.com/GitHubMotiar/My-Project_II
theme:
  logo : /images/ibase-t small logo.png
  icon:
    repo: /images/gitcons/git-pull-request.svg
  language: en
  favicon: /images/book.svg
  plugins:
    - typeset
    - search
  palette:
    # Pallet toggle for dark mode
    scheme: default
    primary: black
    accent: deep orange
    toggle:
      icon: material/weather-night
      name: Switch to light mod

  name: material

  # repo_name: GitHubMotiar/My-Project_II.git

  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - header.autohide
    - announce.dismiss
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.indexes
    - content.code.copy
    # - toc.follow
    # - toc.integrate
extra:
  social:
    # - icon: /images/giticons/mark-github.svg
    #   link: https://github.com/GitHubMotiar
  generator: false
nav:
  - Knowledge Base:
      - 'start here': knowledge_base/start.md
      - 'Code Block': knowledge_base/code_block.md
  - 'Start here'
  - 'Home.md'
  - 'About.md'
  - 'G-Series.md'
  - 'iSeries.md'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
